const DEBUG_SHOW_DEBUG_INFORMATION_KEY = 'showSessionDebugViews';
const DEBUG_SHOW_PAGE_CONTAINER_KEY = 'showPageContainerDebugColor';
const POST_LOGIN_REDIRECT_LOCATION_KEY = 'post-login-redirect-location';
const PRIVACY_PREFERENCES_KEY = 'privacy_preferences_v2';
const SESSION_COOKIE_KEY = 'session_v2';

export {
  DEBUG_SHOW_DEBUG_INFORMATION_KEY,
  DEBUG_SHOW_PAGE_CONTAINER_KEY,
  POST_LOGIN_REDIRECT_LOCATION_KEY,
  PRIVACY_PREFERENCES_KEY,
  SESSION_COOKIE_KEY,
};
export default {
  DEBUG_SHOW_DEBUG_INFORMATION_KEY,
  DEBUG_SHOW_PAGE_CONTAINER_KEY,
  POST_LOGIN_REDIRECT_LOCATION_KEY,
  PRIVACY_PREFERENCES_KEY,
  SESSION_COOKIE_KEY,
};
