export const KEY = 'consent';
export const CONSENT = `app/${KEY}/CONSENT`;
export const DEFER_CONSENT = `app/${KEY}/DEFER_CONSENT`;
export const RE_PROMPT_CONSENT = `app/${KEY}/RE_PROMPT_CONSENT`;
export const RESET_CONSENT = `app/${KEY}/RESET_CONSENT`;

export const CONSENT_STATE_UNSET = 'CONSENT_STATE_UNSET';
export const CONSENT_STATE_ALLOWED = 'CONSENT_STATE_ALLOWED';
export const CONSENT_STATE_DEFERRED = 'CONSENT_STATE_DEFERRED';
export const CONSENT_STATE_REQUIRED = 'CONSENT_STATE_REQUIRED';

export const CONSENT_STATE_ALLOWED_CLIENT_KEY = 'CONSENT_ALLOWED';
export const CONSENT_STATE_DEFERRED_CLIENT_KEY = 'CONSENT_DEFERRED';
