name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: print job details
        run: |
          echo "github_ref ${{ github.ref }}"
          echo "github_event_name ${{ github.event_name }}"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: gg-webapp setup
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm run gg-webapp-install && npm run gg-webapp-transpile

      - name: npm install
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci

      - name: lint
        run: npm run lint

      - name: jest test
        run: npm test

  # snapshot-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Checkout the repo
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.head_ref }}

  #     - name: run snapshot tests
  #       run: |
  #         ./scripts/docker/prepare.sh
  #         ./scripts/docker/run-tests.sh

  #     - name: save snapshots
  #       if: failure()
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: bitmaps_reference
  #         path: backstop_data/bitmaps_reference

  deploy:
    runs-on: ubuntu-latest
    # needs: [test, snapshot-test]
    needs: [test]
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: generate hash
        run: |
          HASH=$(date | md5sum | cut -d ' ' -f 1)
          ZIP_FILE_NAME="webapp-boilerplate---$HASH"
          echo "HASH=$HASH" >> $GITHUB_ENV
          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV

      - name: install system dependencies
        run: sudo apt install -y qemu-user-static binfmt-support

      - name: build docker image
        env:
          GSUITE_APP_PASSWORD: ${{ secrets.GSUITE_APP_PASSWORD }}
          GSUITE_EMAIL: ${{ secrets.GSUITE_EMAIL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        run: |
          echo "zipFileName ${{ env.ZIP_FILE_NAME }}"
          zipFileName=${{ env.ZIP_FILE_NAME }}
          /bin/bash ./scripts/docker/export-prod.sh $zipFileName

      - name: deploy
        run: |
          zipFileName=${{ env.ZIP_FILE_NAME }}
          zip -r $zipFileName.zip docker-image.tar meta.json
          echo "${{ secrets.EC2_RSA }}" > ./identityFile.txt
          chmod 400 ./identityFile.txt
          scp -o "StrictHostKeyChecking=no" -i ./identityFile.txt -r ./$zipFileName.zip ubuntu@ec2-13-40-134-151.eu-west-2.compute.amazonaws.com:/home/ubuntu/departure-lounge/
