name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: print job details
        run: |
          echo "github_ref ${{ github.ref }}"
          echo "github_event_name ${{ github.event_name }}"

      - name: system install
        run: |
          sudo apt-get update
          sudo apt-get install -yyq ca-certificates libappindicator1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 gconf-service lsb-release wget xdg-utils fonts-liberation zip

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install
        run: npm ci

      - name: build for snapshot testing
        run: npm run build:test

      - name: lint
        run: npm run lint

      - name: jest
        run: npm run test

      - name: snapshot test
        run: npm run backstopjs:test

      - name: save snapshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: bitmaps_reference
          path: backstop_data/bitmaps_reference

      - name: commit changes to branch
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Snapshot changes
          push_options: --force

      - name: deploy
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ] && [ "${{ github.event_name }}" != "pull_request" ]; then
            echo "${{ secrets.EC2_RSA }}" > ./identityFile.txt
            chmod 400 ./identityFile.txt
            npm run build
            zip -r build build
            scp -o "StrictHostKeyChecking=no" -i ./identityFile.txt -r ./build.zip ubuntu@ec2-35-178-235-11.eu-west-2.compute.amazonaws.com:/home/ubuntu/webapp-boilerplate/
          fi;
